version: "3.9"

services:
  mongo:
    image: mongo:8.2
    container_name: webapp-mongo
    restart: always
    environment:
      # Utilisateur root de Mongo
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      # Base créée par défaut (même nom que dans appsettings.json: "webapp")
      - MONGO_INITDB_DATABASE=webapp
    ports:
      # Expose Mongo en local (optionnel, mais pratique pour debug avec Compass, etc.)
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    image: todo-backend:latest
    container_name: webapp-go
    environment:
      # Port d'écoute du serveur Go (main.go utilise PORT sinon 5000 par défaut)
      - PORT=5000

      # Variables de connexion Mongo, identiques à la logique de ton TodoService C#
      - DB_ADDRESS=mongo
      - DB_PORT=27017
      - DB_USERNAME=root
      - DB_PASSWORD=example

      # Pour le ColorService (équivalent BACKGROUND_COLOR)
      - BACKGROUND_COLOR=#FFCC00
    depends_on:
      - mongo
    ports:
      # Accès à l'API Go depuis ta machine
      - "5000:5000"

  front:
    image: todo-frontend:latest
    container_name: webapp-angular
    depends_on:
      - api
    ports:
      - "8080:80"

volumes:
  mongo-data:
