version: "3.9"
services:
  webapp:
    image: yannisbourree/exo-webapp-dotnet:1.02
    restart: always
    ports:
      - 80:80
    environment: 
      BACKGROUND_COLOR: "#DD7713"

  frontend:
    image: yannisbourree/exo-front-angular:1.01
    ports:
      - 81:81

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes: 
      - "db_volume:/data/db"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

volumes:
  db_volume: